#!/usr/bin/env python3
'''Cryptocurrency

Displays updated summary of cryptocurrency portfolio.

usage:
    cryptocurrency [options] [<accounts>...]

options:
    -C <dir>, --config-dir  <dir>    directory that holds transactions file
    -c, --cost                       show cost
    -p, --prices                     show prices rather than portfolio
    -T, --transactions               show transactions with portfolio
    -t, --tokens                     show number of tokens held
    -i, --insecure                   do not check certificate of prices website
    -P, --proxy                      connect to the internet through a proxy

You can also override the current price of cryptocurrencies to examine what-if 
scenarios.  Any account specified that contains an '=' is taken to be an 
override, and must be specified as a name=value pair, where name is the name of 
the currency and value is its value in US dollars.  For example:

    cryptocurrency BTC=100k
'''

import requests
from inform import (
    Color, cull, display, done, error, fatal, join, os_error, warn, render_bar
)
from textwrap import dedent
from quantiphy import Quantity, UnitConversion, UnknownConversion
from cryptocurrency import Currency, accounts
from appdirs import user_config_dir
from shlib import to_path
from docopt import docopt
import arrow

TRANSACTIONS_FILENAMES = 'transactions.gpg transactions'
Quantity.set_prefs(prec=2, map_sf=Quantity.map_sf_to_greek)
credit = Color('green')
debit = Color('red')
proxies = dict(
    # The local socks5 proxy on port 9997.
    # Use this at TI because they block access to cryptocompare.
    http='socks5://localhost:9997',
    https='socks5://localhost:9997',
)
reference_currencies = 'BTC EOS ETH USD'.split()

# read the command line
cmdline = docopt(__doc__)
desired_accounts = cmdline['<accounts>']
show_transactions = cmdline['--transactions']
show_tokens = cmdline['--tokens']
show_prices =  cmdline['--prices']
show_cost =  cmdline['--cost']
insecure = cmdline['--insecure']
if insecure:
    requests.packages.urllib3.disable_warnings()
use_proxy = cmdline['--proxy']
if not use_proxy:
    proxies = None

# find the transactions file
if not show_prices:
    settings_dir = cmdline['--config-dir']
    if not settings_dir:
        settings_dir = user_config_dir('cryptocurrency')
    for filename in TRANSACTIONS_FILENAMES.split():
        transactions_filepath = to_path(settings_dir, filename)
        if transactions_filepath.exists():
            break
    else:
        #fatal('transactions file not found in:', settings_dir)
        show_prices = True
    try:
        from avendesora.gpg import PythonFile
    except ImportError:
        show_prices = True

# download latest asset prices from cryptocompare.com
currencies = dict(
    fsyms=','.join(Currency.units()),      # from symbols
    tsyms=','.join(reference_currencies),  # to symbols
)
url_args = '&'.join(f'{k}={v}' for k, v in currencies.items())
base_url = f'https://min-api.cryptocompare.com/data/pricemulti'
url = '?'.join([base_url, url_args])
try:
    r = requests.get(url, proxies=proxies, verify=not insecure)
except KeyboardInterrupt:
    done()
except Exception as e:
    # must catch all exceptions as requests.get() can generate a variety based 
    # on how it fails, and if the exception is not caught the thread dies and 
    # the prices mysteriously stop updating.
    if 'certificate verify failed' in str(e):
        fatal('certificate verify failed for', base_url)
    fatal('cannot access cryptocurrency prices:', codicil=str(e))

try:
    data = r.json()
except:
    try:
        to_path('error.html').write_text(r.text)
    except:
        fatal('cryptocurrency price download was garbled.')
    fatal('cryptocurrency price download was garbled (look in ./error.html for response).')


# Create unit conversions
for each in Currency.__subclasses__():
    for ref in reference_currencies:
        currency = Currency.currency(ref)
        each.converter(cull([currency.SYMBOL, currency.UNITS]), data)

# get current time
now = arrow.now().format('h:mm A, dddd MMMM D')

if show_prices:
    display(f'Prices as of {now}:')
    for c in Currency.currencies():
        try:
            display(f'    {c.one:<7s} = {c.one:<7q$} {c.one:<7qɃ} {c.one:<7qΞ} {c.one:qȄ}')
        except UnknownConversion:
            pass
    done()

# read the transactions
try:
    transactions = PythonFile(transactions_filepath)
except Error as e:
    e.terminate()
transactions.initialize()
transactions.run()
    # running the transactions file causes accounts to be set as a side effect

# process the specified accounts, some of which may actually be overrides
overrides = [n for n in desired_accounts if '=' in n]
desired_accounts = [n for n in desired_accounts if '=' not in n]
if not desired_accounts:
    desired_accounts = [n for n in accounts.keys() if accounts[n].default]

# implement price overrides
for override in overrides:
    try:
        n, v = override.split('=')
        c = Currency.currency(n)
        was = f'rather than {c.one:q$}' if c else '(not found)'
        v = Quantity(v, '$')
        UnitConversion(('USD', v.units), n, slope=v)
        display(f'Override: {n} = {v:q$} {was}.')
    except ValueError:
        fatal('garbled override, expected name=value.', culprit=override)
if overrides:
    display()

holdings = []
for name in desired_accounts:
    try:
        acct = accounts[name]
    except KeyError:
        error('unknown account.', culprit=name)
        continue
    if show_transactions:
        display()
        display(f"{name.title()}'s Transactions:")
        for t in acct.transactions:
            price = t.tokens.price
            value = f'{t.tokens} @ {price}' if price else str(t.tokens)
            if value[0] == '-':
                value = value[1:]
                ttype = 'debit'
                color = debit
            else:
                ttype = 'credit'
                color = credit
            cost = t.cost if t.cost else t.tokens.in_dollars()
            cost = f'({cost})' if cost else None
            comment = f'-- {t.comment}' if t.comment else None
            prefix = '    ' + ' '.join(cull([t.date, ttype])) + ':'
            display(color(*cull([prefix, value, cost, comment])))


    if show_tokens:
        display(f"{name.title()}'s tokens as of {now}:")
        for k in sorted(acct.totals):
            display(f'    {acct.totals[k]:.4P}')
        display()

    title = f"{name.title()}'s holdings as of {now}:"
    currency = {}
    total = acct.total_value()
    largest_share = acct.largest_share()
    for symbol in Currency.names():
        if symbol in acct.totals:
            tokens = acct.totals[symbol]
            try:
                value = tokens.scale('$')
            except UnknownConversion as e:
                warn(e)
                continue
            tokens = tokens.scale(symbol)
            share = value / total
            price = Quantity(1, symbol).scale('$')
            row = f'{tokens:>11q} = {value:<7q} {share:.0%}'
            if show_cost:
                extra = ['{:23s}'.format(f'price={price} per {symbol}')]
                if symbol in acct.purchased:
                    cost = acct.costs[symbol]
                    purchased = acct.purchased[symbol]
                    avg_cost = Quantity(cost/purchased, '$')
                    extra += ['{:27s}'.format(f'cost={avg_cost} for {purchased}')]
                    if avg_cost:
                        gain = (price - avg_cost)/avg_cost
                        extra += [f'gain={gain:.0%}']
                currency[value] = f"    {row:25s}  {' '.join(extra)}".rstrip()
            else:
                bar = render_bar(value/largest_share, 55)
                amount = f'{tokens:>11q} = {value:<6q} @ {price}/{symbol}'
                currency[value] = "    {:35s}  {:5.1%}  {}".format(amount, share, bar)

    cost = acct.total_cost()
    if cost:
        delta = Quantity(total-cost, '$')
        gain = (total-cost)/cost
        combined = f'        Total = {total:<13}  {gain:.0%} ({delta}) gain on {cost} investment'
    else:
        combined = f'        Total = {total}'
    summary = (
        [title] +
        [currency[v] for v in sorted(currency, reverse=True)] +
        [combined]
    )
    holdings.append(join(*summary, sep='\n'))

display(*holdings, sep='\n\n')

#try:
#    from networth import total as non_crypto_total
#    networth = Quantity(total + non_crypto_total, '$')
#    percentage = total / networth
#    display(f'    Net Worth = {networth}  {percentage:.1%}')
#except ImportError:
#    pass
